# Site
title: Arthur Hammer
description: I'm Arthur Hammer, I write software.
author:
  name: Arthur Hammer
  email: arthur@ahammer.me
  github:  arthurhammer
  stackoverflow: 4994382
repo: https://github.com/arthurhammer/ahammer.me

# Build
url: "http://ahammer.me"
permalink: /:year/:title/
host: 0.0.0.0

include:
  - .htaccess
  - _pages
exclude:
  - _private
  - README.MD,
  - LICENSE
  - vendor

defaults:
  -
    scope:
      path: ""  # empty for all files
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/minibundle

markdown: kramdown
highlighter: rouge

# jekyll-paginate
paginate: 7
paginate_path: "/blog/:num/"

# jekyll-seo-tag
social:
  name: Arthur Hammer
  links:
    - https://github.com/arthurhammer
    - https://stackoverflow.com/users/4994382
google_site_verification: knvANMeDeDlyFLBmV6H8_CZyVgm0ODw1ZEJEmYh2JQM
